#ifndef T_CONFIG
#define T_CONFIG

#include <JaszczurHAL.h>

#define WATCHDOG_TIME (SECOND * 7)
#define CORE_OPERATION_DELAY 1

#define WIFI_TIMEOUT_MS    (SECOND * 30)
#define NTP_TIMEOUT_MS     (SECOND * 30)
#define PRINT_INTERVAL_MS  (SECOND * 10)
#define HOURS_SYNC_INTERVAL 12

#define EVALUATE_TIME_FOR_RELAY_MS (SECOND)
#define OLED_ACTIVE_WINDOW_MS (SECOND * 15)

#define MAX_AMOUNT_OF_RELAYS 4

#define UDP_PORT 12345
#define DISCOVER_PACKET "AQUA_DISCOVER"
#define RESPONSE_PACKET "AQUA_FOUND"
#define MQTT_RECONNECT_TIME 5000
#define MQTT_TOPIC_STATUS "status-"
#define MQTT_TOPIC_UPDATE "update-"
#define MQTT_TOPIC_TIME_SET "time-"
#define MQTT_TOPIC_SWITCH_SET "switch-"

#define MAX_TIMEOUT (SECOND * 3)
#define MQTT_SOCKET_MAX_TIMEOUT 2
#define MQTT_KEEP_ALIVE 15

#define MAX_FAILED_PINGS 7
#define NEXT_PING_TIME 1500

#endif
